### PR TITLE
changing meter example to req/min to properly reflect the timeframe

### PR DESCRIPTION
**Pull request by lklepner**

### CODE REVIEW

**Comment by Unitech** [comment]
thanks :)

**Comment by celalo** [comment]
I am not sure this is correct. as far as I can see, either README is incorrect or there is a bug in the code. In my experience `samples:1, timeframe: 60` generates req/sec. I needed to set it up as `samples:60, timeframe: 60` to have req/min.

**Comment by emrahcetiner** [comment]
I agree with @celalo 

samples:1, timeframe: 60 generates req/sec
samples:60, timeframe: 60 generates req/min

**Comment by Unitech** [comment]
the documentation has been updated https://github.com/keymetrics/pmx#meter-average-calculated-values

**Pull request merged**
